Repository PlanningBiblio/PlanningBiblio, pull requests merged in 2023-02, with the labels that each got.

#880 MT39696: Set Recup-DelaiDefaut to 0 if not correctly set.
  src/Controller/OvertimeController.php
Labels: master, 22.04.xx, 22.10.xx

#879 MT39491: Fix save agent save when holidays values are empty
  src/Controller/AgentController.php
Labels: master, BSG, 22.04.xx, 22.10.xx

#875 MT39548: Fix models deletion
  src/Controller/ModelController.php
Labels: master, 22.10.xx

#873 MT39958: Display the time of absence registrations
  templates/absences/index.html.twig
Labels: bug, master, 22.04.xx, 22.10.xx

#871 MT39932 - remove HTML entities from frameworks title
  public/setup/atomicupdate/MT39932.php
  public/setup/db_data.php
  public/setup/maj.php
Labels: bug, master, 22.10.xx

#870 MT39895: Add throttle to overtime edits
  src/Controller/OvertimeController.php
Labels: master, BSG

#867 MT39034: Add throttle to holiday edits
  src/Controller/HolidayController.php
Labels: master, BSG, 22.04.xx, 22.10.xx
