Repository PlanningBiblio/PlanningBiblio, pull requests merged in 2023-10, with the labels that each got.

#961 MT41027: Add absence block, correctly define absence hours
  public/absences/js/modif.js
  public/conges/js/script.conges.js
  public/js/script.js
Labels: bug, master

#957 MT42098: importMSGraphCalendar return 0 on success
  src/Cron/ImportMSGraphCalendar.php
Labels: bug, master, 22.10.xx, 23.04.xx

#955 MT42339: Handle SSO tickets in the Login Listener
  src/Controller/AuthorizationsController.php
  src/EventListener/LoginListener.php
Labels: bug, master

#954 MT40642: Add LDIF import capabilities
  config/permissions.yaml
  data/ldif_sample.ldif
  public/setup/atomicupdate/MT40642.php
  public/setup/db_data.php
  src/Controller/AgentController.php
  src/PlanningBiblio/Ldif2Array.php
  templates/agents/import-form.html.twig
  templates/agents/index.html.twig
  templates/agents/ldap-search.html.twig
  tests/Controller/AgentControllerLDIFTest.php
Labels: enhancement, master, 22.10.xx, 23.04.xx

#951 MT41028: Change the warning message for reccuring absences with end date
  public/absences/js/modif.js
  templates/absences/add.html.twig
Labels: enhancement, master

#943 MT41845: Check invitation acceptance when importing ICS events
  public/ics/class.ics.php
Labels: bug, master, 22.10.xx, 23.04.xx

#942 MT41894: Fix warning undefined array key VEVENT when importing ics calendars
  public/ics/class.ics.php
Labels: bug, master, 22.10.xx, 23.04.xx

#937 MT41650: Use utf8-aware function mb_substr (instead of substr) in plannings
  public/planning/poste/fonctions.php
Labels: bug, master, 22.10.xx, 23.04.xx

#823 MT39367: Remove FILTER_SANITIZE_STRING depreciations
  init/init_ajax.php
  public/absences/ajax.piecesJustif.php
  public/conges/ajax.enregistreRecup.php
  public/ics/ajax.resetURL.php
  public/include/ajax.menus.php
  public/include/db.php
  public/include/header.php
  public/include/sanitize.php
  public/ldap/ajax.ldaptest.php
  public/ldap/class.ldap.php
  public/personnel/ajax.delete.php
  public/personnel/ajax.sendICSURL.php
  public/personnel/ajax.update.php
  public/personnel/class.personnel.php
  public/planning/poste/ajax.appelDispoMail.php
  public/planning/poste/ajax.hiddenTables.php
  public/planning/poste/ajax.notes.php
  public/planning/poste/ajax.notifications.php
  public/planning/poste/ajax.updateCell.php
  public/planning/poste/ajax.validation.php
  public/setup/createconfig.php
  public/setup/createdb.php
  public/setup/fin.php
  public/statistiques/export.php
  src/Controller/FrameworkController.php
  src/Controller/IndexController.php
Labels: master, depreciations

#843 Added unit tests for Legal notices
  tests/Controller/LegalNoticesControllerTest.php
Labels: master, Unit tests

#793 Added test for WorkingHour right with Absences-notifications-agent-par-agent
  src/Controller/OvertimeController.php
  tests/Controller/WorkingHourControllerListTest.php
  tests/Controller/WorkingHourControllerStatusesTest.php
Labels: master, Unit tests

#790 Add unit tests for Add Holiday Controller
  tests/Controller/AbsenceControllerNotificationTest.php
  tests/Controller/AbsenceInfoControllerTest.php
  tests/Controller/AdminInfoControllerTest.php
  tests/Controller/AgentControllerListTest.php
  tests/Controller/AgentControllerPasswordTest.php
  tests/Controller/AgentControllerTest.php
  tests/Controller/CalendarControllerTest.php
  tests/Controller/ClosingDayControllerTest.php
  tests/Controller/HolidayControllerAddTest.php
  tests/Controller/HolidayInfoControllerTest.php
  tests/Controller/IndexControllerTest.php
  tests/Controller/OvertimeControllerTest.php
  tests/Controller/PositionControllerTest.php
  tests/Controller/SkillControllerTest.php
Labels: master, Unit tests

#750 1dd Unit test for Add Overtime Controller
  tests/Controller/OvertimeControllerAddTest.php
  tests/Controller/OvertimeControllerTest.php
Labels: master, Unit tests
