Repository PlanningBiblio/PlanningBiblio, pull requests merged in 2023-12, with the labels that each got.

#980 MT42875: Week number in week cycle should not be reset on new year
  public/include/function.php
  public/setup/atomicupdate/MT42875_updateDateDebutPl.php
  tests/Class/ClassDatePlTest.php
Labels: bug, master, 23.04.xx, 23.10.xx

#976 MT42872: add symfony/mime to display attachments
  composer.json
  composer.lock
Labels: bug, master, 23.10.xx

#970 MT40023: Stats/Agent: Do not show agents never selected and not in selected sites
  public/statistiques/class.statistiques.php
  public/statistiques/export.php
  src/Controller/StatisticController.php
Labels: master, 23.04.xx, 23.10.xx

#965 MT42470: Enhance CSS
  public/activites/js/activites.js
  public/include/header.php
  public/js/CJScript.js
  public/js/plb/framework.js
  public/js/script.js
  public/planning/poste/js/planning.js
  public/themes/default/default.css
  public/themes/default/images/icon/logout_black_24dp.svg
  public/themes/default/images/icon/logout_green_24dp.svg
  templates/base.html.twig
  templates/framework/edit_tab.html.twig
  templates/login.html.twig
Labels: enhancement, master, CSS, 23.04.xx, 23.10.xx

#963 MT42541: Fix migration scripts
  public/setup/maj.php
  tools/fix_encoding_issues.php
  tools/remove_html_entities_from_absence_reasons.php
Labels: bug, master, 23.04.xx, 23.10.xx
