Repository PlanningBiblio/PlanningBiblio, pull requests merged in 2023-11, with the labels that each got.

#975 MT42530 : Filter by site the list of presents displayed under the schedules
  public/setup/atomicupdate/KB10974.php
  public/setup/db_data.php
  src/Controller/IndexController.php
  src/PlanningBiblio/PresentSet.php
  templates/planning/poste/index.html.twig
Labels: enhancement, master

#974 MT40171: Rename Planning Biblio to Planno
  public/include/function.php
  public/planningHebdo/class.planningHebdo.php
  public/setup/atomicupdate/MT40171.php
  public/setup/db_data.php
  src/Controller/AgentController.php
  src/Controller/AjaxController.php
  src/PlanningBiblio/Notifier/Messages/create_account.php
  templates/absences/edit.html.twig
  templates/help/index.html.twig
  tests/PlanningBiblio/NotifierTest.php
Labels: master, 23.04.xx, 23.10.xx

#971 MT42596: Escape teleworking reasons on planning context menu
  public/absences/class.absences.php
  src/Controller/PlanningJobController.php
Labels: bug, master, 22.10.xx, 23.04.xx, 23.10.xx

#969 MT42693: Disable Absence Block on Planook config
  templates/admin/index.html.twig
  tools/set_planook_config.sql
  tools/unset_planook_config.sql
Labels: master, Planook, 23.10.xx

#968 MT41900: Replace HTTP method DEL with DELETE
  public/js/script.js
  src/Controller/AbsenceInfoController.php
  src/Controller/AdminInfoController.php
  src/Controller/HolidayInfoController.php
  src/Controller/ModelController.php
  templates/admin/model/index.html.twig
Labels: bug, master, 22.10.xx, 23.04.xx, 23.10.xx

#966 MT40009: Fix comp time display in 'My Account' when negative
  public/include/function.php
  tests/Include/IncludeFunctionTest.php
Labels: bug
