Repository PlanningBiblio/PlanningBiblio, pull requests merged in 2023-04, with the labels that each got.

#897 MT40252: don't show the alert "select more than 1 year", follow up
  public/absences/js/voir.js
Labels: bug, master, 22.04.xx, 22.10.xx

#896 MT40456: fix error 'La demande doit être effectuée dans les 0 jours' …
  src/Controller/OvertimeController.php
Labels: bug, master, 22.04.xx, 22.10.xx

#883 MT39529: Fix erroneous message on absence add
  public/absences/class.absences.php
  src/Controller/AbsenceController.php
  src/Model/Agent.php
  tests/Model/AgentTest.php
Labels: master, 22.04.xx, 22.10.xx

#899 MT39836: interpret html tags on comments in weekly view
  templates/planning/poste/week.html.twig
Labels: bug, master, 22.10.xx

#779 Mt37227 22.04.xx
  public/planning/poste/index.php
  public/themes/default/default.css
  templates/absenceInfo/index.html.twig
  templates/absences/index.html.twig
  templates/admin/model/index.html.twig
  templates/adminInfo/index.html.twig
  templates/agents/index.html.twig
  templates/comp_time/index.html.twig
  templates/conges/index.html.twig
  templates/framework/index.html.twig
  templates/holidayInfo/index.html.twig
  templates/myAccount.html.twig
  templates/planning/poste/index.html.twig
  templates/position/index.html.twig
  templates/skill/index.html.twig
  templates/statistics/absence.html.twig
  templates/statistics/attendeesmissing.html.twig
  templates/statistics/positionsummary.html.twig
  templates/statistics/saturday.html.twig
  templates/statistics/time.html.twig
  templates/workinghour/index.html.twig
Labels: enhancement, 22.04.xx

#903 MT40682: Correctly set displayed version
  init/init.php
  public/init.php
Labels: bug, master, 22.04.xx, 22.10.xx

#901 MT39894: disable calendar synchronizations for new agents by default
  src/Controller/AgentController.php
  templates/agents/edit.html.twig
Labels: bug, master, 22.10.xx
