Repository PlanningBiblio/PlanningBiblio, pull requests merged in 2023-06, with the labels that each got.

#916 MT40668: ICS export with absences (with links and help udpated)
  public/ics/calendar.php
  public/ics/class.ics.php
  public/js/script.js
  public/lang/fr_FR.php
  public/personnel/ajax.sendICSURL.php
  public/personnel/js/modif.js
  public/setup/atomicupdate/MT40668.php
  public/setup/db_data.php
  templates/agents/edit.html.twig
  templates/help/index.html.twig
  templates/myAccount.html.twig
  tests/Controller/AbsenceInfoControllerTest.php
  tests/Controller/HolidayInfoControllerTest.php
Labels: enhancement, master

#930 MT41151: Allow /holiday/accounts to be displayed in days
  public/conges/class.conges.php
  templates/conges/accounts.html.twig
Labels: bug, master, 22.10.xx

#928 MT41068: Fix absence statistics display when PlanningHebdo is disabled
  templates/statistics/absence.html.twig
Labels: bug, master, 22.10.xx

#925 MT41168: Fix the site selection on statistics / absences
  src/Controller/StatisticController.php
  templates/statistics/absence.html.twig
Labels: bug, master, 22.10.xx, 23.04.xx

#924 MT41142: Color the logged in agent
  public/include/sanitize.php
  public/planning/poste/ajax.updateCell.php
  public/planning/poste/fonctions.php
  public/planning/poste/js/planning.js
  public/setup/atomicupdate/MT41142.php
  public/setup/db_data.php
  src/Controller/ConfigController.php
  templates/config/category.html.twig
Labels: enhancement, master

#922 MT41030: Allow to narrow ICS exports to a number of days in the past
  public/ics/calendar.php
  public/ics/class.ics.php
  public/setup/atomicupdate/MT41030.php
  templates/help/index.html.twig
Labels: enhancement, master

#921 MT41028: Show an alert when a recurring absence is added and the enddate is set
  public/absences/js/modif.js
  templates/absences/add.html.twig
Labels: master, 22.10.xx, 23.04.xx

#920 MT39946: Fix time format parameter for ajax call in absence add
  public/absences/js/modif.js
Labels: master, 22.10.xx

#919 MT41131: Fix typo in templates/conges/add.html.twig
  templates/conges/add.html.twig
Labels: master, 22.10.xx, 23.04.xx

#918 MT41094: Don't check journey time between areas when there is only one area
  src/Controller/PlanningJobController.php
Labels: bug, master, 22.10.xx, 23.04.xx

#914 MT40945: Fix the logo's link
  templates/menu.html.twig
Labels: bug, master, 22.10.xx, 23.04.xx

#912 MT40851: Make Statistics/time table not responsive.
  public/js/CJScript.js
  templates/statistics/time.html.twig
Labels: master, CSS, 22.10.xx, 23.04.xx

#892 Mt31709
  src/Controller/AjaxController.php
  src/PlanningBiblio/Helper/HolidayHelper.php
  src/Repository/AgentRepository.php
  tests/Repository/AgentRepositoryTest.php
Labels: master, 22.10.xx, 23.04.xx

#923 MT40199 : Remove the padlock when deleting plannings
  public/planning/poste/js/planning.js
  src/Controller/IndexController.php
Labels: bug, master, 22.10.xx, 23.04.xx

#917 MT41069: Show borders of all cells in statistics tables
  public/themes/default/default.css
  templates/statistics/agent.html.twig
  templates/statistics/position.html.twig
  templates/statistics/service.html.twig
  templates/statistics/status.html.twig
  templates/statistics/supportposition.html.twig
Labels: bug, master, CSS, 22.10.xx, 23.04.xx
