Repository PlanningBiblio/PlanningBiblio, pull requests merged in 2023-03, with the labels that each got.

#889 MT40252: don't show the alert "please select more than 1 year" on leap years
  public/absences/js/voir.js
Labels: bug, master, 22.04.xx, 22.10.xx

#884 MT39693: Show closingday in menu only if Conges-Enable is enabled
  public/include/class.menu.php
  public/setup/atomicupdate/MT39693.php
  public/setup/db_data.php
  tests/Class/ClassMenuTest.php
Labels: master, 22.04.xx, 22.10.xx

#864 MT39412: the datefull twig filter now interpret html tags
  src/Twig/AppExtension.php
Labels: bug, master, 22.10.xx

#877 MT39992: the week view take into account the site parameter
  src/Controller/BaseController.php
  src/Controller/IndexController.php
  src/Controller/WeekPlanningController.php
Labels: bug, master, 22.10.xx

#893 MT38947: Fix display of groups-free position in time statistics
  src/Controller/StatisticController.php
Labels: master, 22.04.xx, 22.10.xx
